name: Update README Stats

on:
  push:
    branches:
      - main # Or your default branch name

jobs:
  update-stats:
    runs-on: ubuntu-latest
    # Prevent running on forks unless specifically intended
    if: github.repository == 'theboringdotapp/unsubscriber' # IMPORTANT: Replace with your actual repo path

    permissions:
      # Need write access to push the updated README
      contents: write

    steps:
      - name: Checkout Full History
        uses: actions/checkout@v4
        with:
          # Need full history for the time estimator script
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Use a recent Python 3 version

      - name: Generate Stats
        id: generate_stats
        run: |
          # Run the script and redirect output to a temporary file
          python git_time_estimator.py > stats_output.txt
          # Base64 encode the file content and write to GITHUB_OUTPUT
          # Use -w 0 for base64 to prevent line wrapping
          encoded_stats=$(base64 -w 0 stats_output.txt)
          echo "stats_content_b64=$encoded_stats" >> $GITHUB_OUTPUT
          # Clean up the temporary file
          rm stats_output.txt

      - name: Update README
        id: update_readme
        run: |
          chmod +x .github/scripts/update_readme.py
          # Decode the Base64 stats content before passing to the script
          decoded_stats=$(echo "${STATS_CONTENT_B64}" | base64 -d)
          # Pass decoded content via environment variable
          export STATS_CONTENT="$decoded_stats"
          python .github/scripts/update_readme.py README.md
        env:
          # Pass the Base64 encoded content from the previous step
          STATS_CONTENT_B64: ${{ steps.generate_stats.outputs.stats_content_b64 }}

      - name: Commit and Push Changes
        if: steps.update_readme.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "chore: Update README stats [skip ci]"
          git push
