name: Update README Stats

on:
  push:
    branches:
      - main # Or your default branch name

jobs:
  update-stats:
    runs-on: ubuntu-latest
    # Prevent running on forks unless specifically intended
    if: github.repository == 'theboringdotapp/unsubscriber' # IMPORTANT: Replace with your actual repo path

    permissions:
      # Need write access to push the updated README
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Calculate Git Time Stats
        uses: theboringdotapp/git-time-stats-action@0.2
        with:
          readme-path: "README.md" #
          session-gap: 45 # Minutes gap between sessions
          min-session: 5 # Minimum session duration in minutes
          max-session: 4 # Maximum session duration in hours Default is README.md
